// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';

var Root        = require("./root.js");
var ReactDOMRe  = require("reason-react/lib/js/src/reactDOMRe.js");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

require("../../../src/styles.css");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Root.make(/* array */[])), "app");

/*  Not a pure module */
