// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';


var fakeUsers = /* :: */[
  /* record */[
    /* firstName */"Brandon",
    /* lastName */"Dail",
    /* nickname */"aweary",
    /* id */-2056091981,
    /* status : Available */0,
    /* picture */"http://www.img.com",
    /* roles : :: */[
      "hacker",
      /* [] */0
    ]
  ],
  /* :: */[
    /* record */[
      /* firstName */"Eli",
      /* lastName */"Kinsey",
      /* nickname */"disce",
      /* id */506120076,
      /* status : DoNotDisturb */2,
      /* picture */"http://www.img.com",
      /* roles : [] */0
    ],
    /* [] */0
  ]
];

exports.fakeUsers = fakeUsers;
/* No side effect */
