// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';

var Chat        = require("./components/chat.js");
var Block       = require("bs-platform/lib/js/block.js");
var Curry       = require("bs-platform/lib/js/curry.js");
var React       = require("react");
var ChannelList = require("./components/channelList.js");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

var component = ReasonReact.statefulComponent("Root");

function make() {
  var handleNewMessage = function (messageText, param) {
    var state = param[/* state */3];
    console.log(messageText);
    console.log(state[/* messages */0]);
    var messages = state[/* messages */0].concat(/* array */[/* record */[
            /* content */messageText,
            /* author */1,
            /* id */22
          ]]);
    return /* Update */Block.__(0, [/* record */[/* messages */messages]]);
  };
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (self) {
      var foo = Curry._1(self[/* update */2], handleNewMessage);
      return React.createElement("div", {
                  className: "app-container"
                }, ReasonReact.element(/* None */0, /* None */0, ChannelList.make(/* array */[])), ReasonReact.element(/* None */0, /* None */0, Chat.make(foo, self[/* state */3][/* messages */0], /* array */[])));
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[/* messages : array */[]];
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/* component Not a pure module */
