// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

var component = ReasonReact.statelessComponent("ChannelList");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("ul", {
                  className: "channel-list"
                }, React.createElement("li", {
                      className: "channel-list--item channel-active-item"
                    }, "# general"), React.createElement("li", {
                      className: "channel-list--item"
                    }, "# reasonml"), React.createElement("li", {
                      className: "channel-list--item"
                    }, "# react"));
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/* component Not a pure module */
