// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

var component = ReasonReact.statelessComponent("ChatMessage");

function make(message, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("li", {
                  className: "chat-message"
                }, React.createElement("img", {
                      className: "user-avatar",
                      src: "https://semantic-ui.com/images/avatar2/large/matthew.png"
                    }), React.createElement("div", {
                      className: "chat-message--content"
                    }, React.createElement("div", undefined, React.createElement("span", {
                              className: "chat-message--user"
                            }, "Aweary "), React.createElement("span", {
                              className: "chat-message--time"
                            }, "Today at 12:30")), React.createElement("div", {
                          className: "chat-message--text"
                        }, message[/* content */0])));
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/* component Not a pure module */
