// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';

var React        = require("react");
var MessageList  = require("./messageList.js");
var ReasonReact  = require("reason-react/lib/js/src/reasonReact.js");
var MessageInput = require("./messageInput.js");

var component = ReasonReact.statelessComponent("Content");

function make(messages, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: "content"
                }, ReasonReact.element(/* None */0, /* None */0, MessageList.make(messages, /* array */[])), ReasonReact.element(/* None */0, /* None */0, MessageInput.make(/* array */[])));
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/* component Not a pure module */
