// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';

var Block       = require("bs-platform/lib/js/block.js");
var Curry       = require("bs-platform/lib/js/curry.js");
var React       = require("react");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

var component = ReasonReact.statefulComponent("Foo");

function make(onNewMessage, _) {
  var handleChange = function ($$event, _) {
    var target = $$event.target;
    return /* Update */Block.__(0, [/* record */[/* value */target.value]]);
  };
  var handleKeyDown = function ($$event, param) {
    var state = param[/* state */3];
    var keyCode = $$event.keyCode;
    if (keyCode === 13 && !$$event.shiftKey) {
      $$event.preventDefault();
      if (state[/* value */0] !== "") {
        Curry._1(onNewMessage, state[/* value */0]);
      }
      return /* Update */Block.__(0, [/* record */[/* value */""]]);
    } else {
      return /* NoUpdate */0;
    }
  };
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (self) {
      return React.createElement("form", {
                  className: "message-input"
                }, React.createElement("textarea", {
                      value: self[/* state */3][/* value */0],
                      onKeyDown: Curry._1(self[/* update */2], handleKeyDown),
                      onChange: Curry._1(self[/* update */2], handleChange)
                    }));
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[/* value */""];
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/* component Not a pure module */
